// Document types for file uploads
export enum DocumentType {
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  COVER_PICTURE = 'COVER_PICTURE',
  BLOG_IMAGE = 'BLOG_IMAGE',
  COURSE_IMAGE = 'COURSE_IMAGE',
  MATERIAL_IMAGE = 'MATERIAL_IMAGE',
  ADVERT_IMAGE = 'ADVERT_IMAGE',
  GENERAL_IMAGE = 'GENERAL_IMAGE',
  STORE_IMAGE = 'STORE_IMAGE',
  EVENT_FLYER = 'EVENT_FLYER',
}
