name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install dependencies
      run: pnpm install

    - name: Build application
      run: pnpm build

  deploy-dev:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Dev EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_EC2_HOST }}
        username: ${{ secrets.DEV_EC2_USER }}
        key: ${{ secrets.DEV_EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/atc-africa-backend-replica
          git pull origin main
          pnpm install
          pnpm db:generate
          pnpm build
          pm2 restart atc-africa-api-dev || pm2 start dist/src/main.js --name atc-africa-api-dev
          pm2 save